### ISSUE TITLE
Tipps

### ISSUE THREAD

**Issue by AlexanderEggers** [NinjaHubHH/BombBob#1]
Hallo zusammen,

ich hab mir mal euer Projekt angeschaut und mir sind ein paar Punkt aufgefallen, die euch eventuell weiterhelfen könnten:
1. Speichert den aktuellen Spielstand in sogenannte "SharedPreferences". Diese können primitive Datentypen halten. Zudem müsst ihr bedenken, dass das Schließen der App alle Daten innerhalb der App löscht. Dies kann nur umgegangen werden wenn die Daten in SharedPreferences oder ähnliches gespeichert wurden. Natürlich müsst ihr dadurch im Code auch bedenken wie und wo ihr diese Daten wieder ladet. (mehr dazu im 2. Punkt)
2. Baut euch eine AppStart Aktivität, die gleichzeitig als Hauptaktivität bzw. Start Aktivität agieren wird. Diese ist nur dafür zuständig sozusagen das korrekte Event zu starten, die Zeit zu setzen usw. Mithilfe der SharedPreferences könntet ihr an dieser Stelle den alten Speicherstand laden und an der gleichen Stelle das Spiel fortsetzen. Diese Aktivität wird also via Intent andere Aktivitäten auf Basis gewisser Werte starten.
3. Arbeitet mit möglichst einfachen Implementierungen. Heißt Threads, endlos Schleifen oder ähnliches solltet ihr möglichst verhindern - besonders auf dem GUI Thread. Solltet ihr wirklich mal einen anderen Thread brauchen oder Berechnungen durchführen die sehr viel Rechenpower brauchen, dann verwendet die "AsyncTask" Implementierung von Android. Meine Empfehlung: Ihr solltet die App dafür mindestens auf "TargetSDK 16" stellen. 
4. Zum Thema Zeit: Wie schon 3. erklärt versucht möglichst einfache Implementierungen zu verwenden. So würde es für diese Implementierung Sinn machen mit der Java Umsetzung "System.currentTimeMillis" zu arbeiten. Diese gibt euch ein Long zurück welches die aktuelle Zeit hält. Um die Zeit daraus wieder zu bekommen könnt ihr das "Calendar" Objekt verwenden. Es gibt dazu ein paar sehr gute Beispiele im Netz, einfach mal nach suchen.
5. Versucht eure Variablen, welche von der App global verwendet werden müssen, in eine separate Klasse zu hauen. Diese speichert diese Variablen als "public static final ... " oder "public static ... " sodass ihr einfach über diese Klasse auf alle relevanten Werte zugreifen könnt. Außerdem bekommt ihr dadurch einen guten Überblick über alle relevanten Werte und könnt dadurch besser Tweaking später betreiben.

Sollte mir noch was einfallen, haue ich das hier rein. Sonst gerne her mit den Fragen wenn ihr noch was habt. Wie erwähnt nehm ich mir gerne noch ein Abend für euch Zeit, meldet das aber bitte so früh wie möglich an, weil ich zurzeit sehr viel um die Ohren habe.

**Comment by DerBergdoktor** [comment]
Erstmal vielen Dank für das Feedback.
Das mit den SharedPreferences klingt sehr sinnvoll. Wir versuchen das mal demnächst umzusetzen. Falls jemand Probleme hat, würde er sich ggf nochmal bei dir deswegen melden. Das mit den Variablen klingt auch gut. Ich wurde häufig gewarnt statics zu benutzen, aber solange es klappt :D
Beim Timer haben wir mit dem Thread zwar nicht den besten Ansatz, aber ich glaube ich weiß wo das Problem bisher da war, wenn er funktioniert bleiben wir glaub ich erstmal dabei. Falls nicht, würde ich was die Systemzeit anbelangt nochmal auf dich zurückkommen.

**Comment by AlexanderEggers** [comment]
Wie gesagt, dass mit dem separaten Thread für den Timer ist eine unglaubliche Performance Schleuder im Vergleich und teilweise auch sehr unsauber. Außerdem lässt sich dieser Timer Wert sehr schlecht abspeichern.

PS: Haut eure Fragen am besten direkt in diesen Task oder erstellt neue und haut mich als "Assignee" rein.
